### ISSUE TITLE
Odd behavior while using 3rd party camera apps while using flash

### ISSUE THREAD

**Issue by RohanAJoshi** [CyanogenMod/android_device_oneplus_oneplus3#1]
I know it's too early for reporting bug when not even nightlies not started.
But currently state perfectly stable for end user like me, just had one bug that was annoying and want to report it. 
Sorry for early reporting. 
When I was testing ROM (unofficial build from xda) at night, I encountered one major bug is camera.
While using Google camera with flash on, there was 2 seconds gap between focus flash and picture taking flash.
Picture taking flash was so bright, and image came totally white.
Most of times 3rd party apps not taking pictures at all while flash on.
Tried Google camera, snap camera, open camera. 
I looked at log, there was lot of errors in camera.
There was error about libwvm.so not found and other errors.
Please find log bellow. 
http://pastebin.com/QZHCYDw9
http://pastebin.com/wMJDm7QC
http://pastebin.com/eiBgbZWK
. 
For repeating bug, take picture using 3rd party camera where flash used for focusing, you will either such or picture comes white. 
I hope you guys will soon solve this.
This is important for me cause stock camera does focus while using flash in dark areas. It's just takes pic. No focus at all.
[2016-07-07-01-30-48.txt](https://github.com/CyanogenMod/android_device_oneplus_oneplus3/files/352596/2016-07-07-01-30-48.txt)
[2016-07-07-11-28-03.txt](https://github.com/CyanogenMod/android_device_oneplus_oneplus3/files/352599/2016-07-07-11-28-03.txt)
[2016-07-07-21-46-30.txt](https://github.com/CyanogenMod/android_device_oneplus_oneplus3/files/352600/2016-07-07-21-46-30.txt)

**Comment by bemolxd** [comment]
Post this bug directly into the thread where you got your unofficial build from.

**Comment by RohanAJoshi** [comment]
Anyone working on this ?

**Comment by RohanAJoshi** [comment]
@cyanogen  : even with latest updates with camera on 30 July nightly this issue remains same. 
And thanks for working on camera.

**Comment by simonsmh** [comment]
This bug still exists.
In some app like telegram we can't make camera focus. That's why oos ported camera FC. This is a serious bug and I hope this bug to be fixed ASAP.
Thanks.

**Comment by TheCrazyLex** [comment]
Fix: https://github.com/AOSPA/android_device_oneplus_oneplus3/commit/001784c53a8df48d207ed6c1ef97e5f808f75014

**Comment by RohanAJoshi** [comment]
fixed with new hal
