### ISSUE TITLE
Crash when connecting to a 5ghz wireless

### ISSUE THREAD

**Issue by shyim** [CyanogenMod/android_device_oneplus_oneplus3#20]
When i connect to a 5ghz wireless network, my phone is everytime crashing and rebooting

**Comment by tomscholz** [comment]
I had a similar situation. I connected my phone to 5ghz network but then my phone was bootlooping so I had to format :/

**Comment by crdoconnor** [comment]
I get this too. There's a certain high speed wireless network that causes my phone to reboot. It usually reboots about ~30 seconds - 2 minutes after connecting.

I once left the wifi turned on in the vicinity of the network (the password was wiped so it couldn't connect) and it triggered a reboot as well.
