### ISSUE TITLE
Cant open third party Camera-APP (Google Camera)

### ISSUE THREAD

**Issue by OP3Newbie12** [CyanogenMod/android_device_oneplus_oneplus3#5]
Hey,

if i open the google camera app i just see a black screen with the camera symbol in the middle, but then it just stays that way. I cant even try to take a picture. Maybe its related to the gallery bug?
Thx in advance.

**Comment by ggogel** [comment]
Yes it is. You should not be able to take photos with any camera app as far as I know #2

**Comment by OP3Newbie12** [comment]
New nightly fixed it.
